import 'classes.dart';

final Map<String, List<ICPPeriod>>week = {
  "Sunday": const [
    ICPPeriod(
      startTime: "7:00AM",
      endTime: "8:30AM",
      moduleCode: "CC4057NP",
      moduleTitle: "Introduction to Information System",
      lecturer: "Mr. Bimesh Shrestha",
      type: "Lecture",
      block: "Nepal",
      room: "SR01 - Fewa",
    ),
    ICPPeriod(
      startTime: "9:30AM",
      endTime: "11:00AM",
      moduleCode: "MA4001NP",
      moduleTitle: "Logic & Problem Solving",
      lecturer: "Mr. Aananda Bhattarai",
      type: "Lecture",
      block: "Nepal",
      room: "Lab01 - Gokyo",
    ),
  ],
  "Monday": const [
    ICPPeriod(
      startTime: "7:00AM",
      endTime: "8:30AM",
      moduleCode: "CS4001NP",
      moduleTitle: "JAVA Programming",
      lecturer: "Mr. Sushil Paudel",
      type: "Lecture",
      block: "Nepal",
      room: "Lab02 - Nilgiri",
    ),
    ICPPeriod(
      startTime: "10:00AM",
      endTime: "11:30AM",
      moduleCode: "CT4005NP",
      moduleTitle: "Computer Hardware & Software Architectures",
      lecturer: "Mr. Badri R. Lamichhane",
      type: "Lecture",
      block: "Nepal",
      room: "SR04 - Tilicho",
    ),
  ],
  "Tuesday": const [
    ICPPeriod(
      startTime: "9:30AM",
      endTime: "11:00AM",
      moduleCode: "MA4001NP",
      moduleTitle: "Logic & Problem Solving",
      lecturer: "Mr. Aananda Bhattarai",
      type: "Tutorial",
      block: "UK",
      room: "Lab03 - Open Access Lab",
    ),
    ICPPeriod(
      startTime: "12:00PM",
      endTime: "1:30PM",
      moduleCode: "CT4005NP",
      moduleTitle: "Computer Hardware & Software Architectures",
      lecturer: "Mr. Amar Khanal",
      type: "Tutorial",
      block: "Nepal",
      room: "SR03 - Rara",
    ),
  ],
  "Wednesday": const [
    ICPPeriod(
      startTime: "7:00AM",
      endTime: "8:30AM",
      moduleCode: "CS4001NP",
      moduleTitle: "JAVA Programming",
      lecturer: "Mr. Sushil Paudel",
      type: "Tutorial",
      block: "UK",
      room: "TR01 - Big Ben",
    ),
    ICPPeriod(
      startTime: "10:00AM",
      endTime: "11:30AM",
      moduleCode: "CT4005NP",
      moduleTitle: "Introduction to Information Systems",
      lecturer: "Mr. Bimesh Shrestha",
      type: "Tutorial",
      block: "Nepal",
      room: "SR01 - Fewa",
    ),
  ],
  "Thursday": const [
    ICPPeriod(
    startTime: "7:00AM",
    endTime: "8:30AM",
    moduleCode: "CT4005NP",
    moduleTitle: "Computer Hardware & Software Architectures",
    lecturer: "Mr. Amar Khanal",
    type: "Lab / Workshop",
    block: "UK",
    room: "TR03 - Thames",
  ),
    ICPPeriod(
      startTime: "9:30AM",
      endTime: "11:00AM",
      moduleCode: "MA4001NP",
      moduleTitle: "Logic & Problem Solving",
      lecturer: "Mr. Aananda Bhattarai",
      type: "Lab / Workshop",
      block: "UK",
      room: "TR03 - Thames",
    ),
  ],
  "Friday": const [
    ICPPeriod(
      startTime: "7:00AM",
      endTime: "8:30AM",
      moduleCode: "CS4001NP",
      moduleTitle: "JAVA Programming",
      lecturer: "Mr. Sushil Paudel",
      type: "Lab / Workshop",
      block: "Nepal",
      room: "SR03 - Rara",
    ),
    ICPPeriod(
      startTime: "9:30AM",
      endTime: "11:00AM",
      moduleCode: "CT4005NP",
      moduleTitle: "Introduction to Information Systems",
      lecturer: "Mr. Bimesh Shrestha",
      type: "Lab / Workshop",
      block: "UK",
      room: "TR03 - Thames",
    ),
  ],
  "Saturday": const [
    ICPPeriod(
      startTime: "7:00AM",
      endTime: "8:30AM",
      moduleCode: "CC4057NP",
      moduleTitle: "Introduction to Information System",
      lecturer: "Mr. Bimesh Shrestha",
      type: "Lecture",
      block: "Nepal",
      room: "SR01 - Fewa",
    ),
    ICPPeriod(
      startTime: "9:30AM",
      endTime: "11:00AM",
      moduleCode: "MA4001NP",
      moduleTitle: "Logic & Problem Solving",
      lecturer: "Mr. Aananda Bhattarai",
      type: "Lecture",
      block: "Nepal",
      room: "Lab01 - Gokyo",
    ),
  ],
};